server:
  port: 8998

spring:
  application:
    name: "Job-Search"
    version: 1.0.2

  datasource:
    url: jdbc:h2:./db/job-search;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
