--changeset Aisha:add_additional_data

-- Вставка 5 работодателей
INSERT INTO USERS (NAME, SURNAME, AGE, EMAIL, PASSWORD, PHONE_NUMBER, ROLE_ID)
VALUES ('Employer1', 'LastName1', 31, 'employer1@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79001111111',
        (select id from ROLES where ROLE = 'EMPLOYER')),
       ('Employer2', 'LastName2', 32, 'employer2@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79002222222',
        (select id from ROLES where ROLE = 'EMPLOYER')),
       ('Employer3', 'LastName3', 33, 'employer3@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79003333333',
        (select id from ROLES where ROLE = 'EMPLOYER')),
       ('Employer4', 'LastName4', 34, 'employer4@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79004444444',
        (select id from ROLES where ROLE = 'EMPLOYER')),
       ('Employer5', 'LastName5', 35, 'employer5@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79005555555',
        (select id from ROLES where ROLE = 'EMPLOYER'));

-- Вставка вакансий для работодателей
INSERT INTO VACANCIES (NAME, DESCRIPTION, CATEGORY_ID, SALARY, EXP_FROM, EXP_TO, IS_ACTIVE, AUTHOR_ID, CREATED_DATE,
                       UPDATE_TIME)
VALUES ('Vacancy 1 for Employer1', 'Description 1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        50000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer1@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 2 for Employer1', 'Description 2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        60000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer1@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 3 for Employer1', 'Description 3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        70000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer1@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Vacancy 1 for Employer2', 'Description 1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        55000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer2@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 2 for Employer2', 'Description 2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        65000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer2@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 3 for Employer2', 'Description 3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        75000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer2@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Vacancy 1 for Employer3', 'Description 1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        60000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer3@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 2 for Employer3', 'Description 2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        70000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer3@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 3 for Employer3', 'Description 3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        80000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer3@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Vacancy 1 for Employer4', 'Description 1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        65000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer4@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 2 for Employer4', 'Description 2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        75000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer4@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 3 for Employer4', 'Description 3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        85000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer4@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Vacancy 1 for Employer5', 'Description 1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        70000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer5@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 2 for Employer5', 'Description 2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        80000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer5@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vacancy 3 for Employer5', 'Description 3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        90000.0, 1, 5, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'employer5@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Вставка 5 соискателей
INSERT INTO USERS (NAME, SURNAME, AGE, EMAIL, PASSWORD, PHONE_NUMBER, ROLE_ID)
VALUES ('Applicant1', 'LastName1', 26, 'applicant1@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79006666666',
        (select id from ROLES where ROLE = 'APPLICANT')),
       ('Applicant2', 'LastName2', 27, 'applicant2@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79007777777',
        (select id from ROLES where ROLE = 'APPLICANT')),
       ('Applicant3', 'LastName3', 28, 'applicant3@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79008888888',
        (select id from ROLES where ROLE = 'APPLICANT')),
       ('Applicant4', 'LastName4', 29, 'applicant4@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79009999999',
        (select id from ROLES where ROLE = 'APPLICANT')),
       ('Applicant5', 'LastName5', 30, 'applicant5@example.com',
        '$2a$12$QplEod5/XykNz0b2QKykru2cLvtimCcEjEyDTihaGwk5qyI7yjeSm', '+79010000000',
        (select id from ROLES where ROLE = 'APPLICANT'));

-- Вставка резюме для соискателей
INSERT INTO RESUMES (NAME, CATEGORY_ID, SALARY, IS_ACTIVE, APPLICANT_ID, CREATED_DATE, UPDATE_TIME)
VALUES ('Resume 1 for Applicant1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        30000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant1@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 2 for Applicant1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        35000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant1@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 3 for Applicant1',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        40000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant1@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Resume 1 for Applicant2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        35000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant2@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 2 for Applicant2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        40000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant2@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 3 for Applicant2',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        45000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant2@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Resume 1 for Applicant3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        40000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant3@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 2 for Applicant3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        45000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant3@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 3 for Applicant3',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        50000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant3@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Resume 1 for Applicant4',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        45000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant4@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 2 for Applicant4',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        50000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant4@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 3 for Applicant4',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        55000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant4@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

       ('Resume 1 for Applicant5',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'it'),
        50000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant5@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 2 for Applicant5',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'разработка'),
        55000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant5@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Resume 3 for Applicant5',
        (SELECT ID FROM CATEGORIES WHERE NAME = 'тестирование'),
        60000.0, TRUE,
        (SELECT ID FROM USERS WHERE EMAIL = 'applicant5@example.com'),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);